#include<stdio.h>
#include<conio.h>
#include<iostream.h>

main()
{
char kode,nama,kelas,harga,total  bayar,jumlah [15];
char MPT, GRD,BTV
long harga=0;

clrscr();
cout<<"Kode Pesawat :";cin>>kode;
cout<<"Nama Pesawat :";cin>>nama;
cout<<"Kelas Pesawat :";cin>>kelas;
cout<<"Harga Tiket :";cin>>harga;

if(kode==MPT)
strcpy(nama,"Merpati");
{
if(kelas=1);
harga=1500000;
else if (kelas=2);
harga=900000;
else
harga=500000;
}

if(kode==GRD)
strcpy(nama,"Garuda");
{
else if(kelas=1);
harga=1200000;
else if (kelas=2);
harga=888800;
else
harga=400000;
}
else if(kode==BTV)
strcpy(nama,"Batavia");
{
if(kelas=1);
harga=1000000;
else if (kelas=2);
harga=700000;
else
harga=300000;
}

else
cout<<"Salah Kode Pesawat"<<endl;

total bayar=harga*jumlah;

cout<<"________________"<<endl;
cout<<"Merk Baju :"<<merk<<endl;
cout<<"Harga Baju :"<<harga<<endl;
getch();
}