#include <stdio.h>
#include <conio.h>
#include <iostream.h>
main()
{

int a,b;
int k1,k2,k3,k4,k5,k6;

clrscr();
cout<<"Masukan Kondisi 1 =";cin>>a;
cout<<"Masukan Kondisi 2 =";cin>>b;
clrscr();

k1= a == b;
k2= a >b ;
k3= a >=b;
k4= a <b;
k5= a <=b;
k6= a !=b ;

cout<<"Operator Relasi C++"<<endl;

cout<<endl;
cout<<"Hasil dari"<<x<<"<"<<y<<"?"<<a<<endl;
cout<<"Hasil dari"<<x<<">"<<y<<"?"<<b<<endl;
cout<<"Hasil dari"<<x<<"!="<<y<<"?"<<c<<endl;
cout<<"Hasil dari"<<x<<"<="<<y<<"?"<<d<<endl;
cout<<"Hasil dari"<<x<<">="<<y<<"?"<<e<<endl;
cout<<"Hasil dari"<<x<<"=="<<y<<"?"<<f<<endl;

getch();
}

